version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    networks:
      - ksrnet1
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  
  notif:
    depends_on:
      - rabbitmq
    build:
      context: LibrarySystem/Library.NotificationService2
    networks:
      - ksrnet1
    ports:
      - "92:80"
    restart: always

  webapi:
    depends_on:
      - rabbitmq
      - notif
    build:
      context: LibrarySystem/Library.WebApi
    networks:
      - ksrnet1
    ports:
      - "91:80"
    restart: always

  web:
    depends_on:
      - rabbitmq
      - webapi
    build:
      context: LibrarySystem/Library.Web
    networks:
      - ksrnet1
    ports:
      - "80:80"
      - "90:90"
      - "93:93"
    restart: always

networks:
  ksrnet1:
    driver: bridge

